name: Build Docusaurus

on: 
  pull_request:
    branches: ["master", "main"]

permissions:
  checks: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache translations
        uses: actions/cache@v3
        with:
          path: .translation-cache
          key: translations-${{ hashFiles('docs/**/*.md') }}
          restore-keys: translations-

      - name: Install dependencies
        run: npm install

      - name: Translate changed files
        run: node translate.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit translations
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add i18n/
          git diff --staged --quiet || git commit -m "Auto-translate markdown files"
          git push origin HEAD:${GITHUB_REF#refs/heads/}

      - name: Build Docusaurus
        run: npm run build
